/*
 * main.h
 * wordlesolvenda
 *
 * Created by Jeremy Rand on 2024-07-17.
 * Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
 *
 */

#ifndef _GUARD_PROJECTwordlesolvenda_FILEmain_
#define _GUARD_PROJECTwordlesolvenda_FILEmain_


#define WS_RES_WINDOW 1001

#define WS_RES_WIN_X 10
#define WS_RES_WIN_Y 25
#define WS_RES_WIN_WIDTH 300
#define WS_RES_WIN_HEIGHT 170

#define WS_RES_CONTROL_LIST 1002

#define WS_RES_BTN_0_0 2001
#define WS_RES_BTN_0_1 2002
#define WS_RES_BTN_0_2 2003
#define WS_RES_BTN_0_3 2004
#define WS_RES_BTN_0_4 2005

#define WS_RES_BTN_1_0 2006
#define WS_RES_BTN_1_1 2007
#define WS_RES_BTN_1_2 2008
#define WS_RES_BTN_1_3 2009
#define WS_RES_BTN_1_4 2010

#define WS_RES_BTN_2_0 2011
#define WS_RES_BTN_2_1 2012
#define WS_RES_BTN_2_2 2013
#define WS_RES_BTN_2_3 2014
#define WS_RES_BTN_2_4 2015

#define WS_RES_BTN_3_0 2016
#define WS_RES_BTN_3_1 2017
#define WS_RES_BTN_3_2 2018
#define WS_RES_BTN_3_3 2019
#define WS_RES_BTN_3_4 2020

#define WS_RES_BTN_4_0 2021
#define WS_RES_BTN_4_1 2022
#define WS_RES_BTN_4_2 2023
#define WS_RES_BTN_4_3 2024
#define WS_RES_BTN_4_4 2025

#define WS_RES_BTN_5_0 2026
#define WS_RES_BTN_5_1 2027
#define WS_RES_BTN_5_2 2028
#define WS_RES_BTN_5_3 2029
#define WS_RES_BTN_5_4 2030

#define WS_RES_BTN_EMPTY_STR 2001

#define WS_RES_BTN_SPACE_X 5
#define WS_RES_BTN_SPACE_Y 2
#define WS_RES_BTN_SPACE_WIDTH 39
#define WS_RES_BTN_SPACE_HEIGHT 14

#define WS_RES_BTN_ROW_0 WS_RES_BTN_SPACE_Y
#define WS_RES_BTN_ROW_1 WS_RES_BTN_ROW_0+WS_RES_BTN_SPACE_HEIGHT+WS_RES_BTN_SPACE_Y
#define WS_RES_BTN_ROW_2 WS_RES_BTN_ROW_1+WS_RES_BTN_SPACE_HEIGHT+WS_RES_BTN_SPACE_Y
#define WS_RES_BTN_ROW_3 WS_RES_BTN_ROW_2+WS_RES_BTN_SPACE_HEIGHT+WS_RES_BTN_SPACE_Y
#define WS_RES_BTN_ROW_4 WS_RES_BTN_ROW_3+WS_RES_BTN_SPACE_HEIGHT+WS_RES_BTN_SPACE_Y
#define WS_RES_BTN_ROW_5 WS_RES_BTN_ROW_4+WS_RES_BTN_SPACE_HEIGHT+WS_RES_BTN_SPACE_Y
#define WS_RES_BTN_ROW_1 WS_RES_BTN_ROW_0+WS_RES_BTN_SPACE_HEIGHT+WS_RES_BTN_SPACE_Y

#define WS_RES_BTN_COL_0 WS_RES_BTN_SPACE_X
#define WS_RES_BTN_COL_1 WS_RES_BTN_COL_0+WS_RES_BTN_SPACE_WIDTH+WS_RES_BTN_SPACE_X
#define WS_RES_BTN_COL_2 WS_RES_BTN_COL_1+WS_RES_BTN_SPACE_WIDTH+WS_RES_BTN_SPACE_X
#define WS_RES_BTN_COL_3 WS_RES_BTN_COL_2+WS_RES_BTN_SPACE_WIDTH+WS_RES_BTN_SPACE_X
#define WS_RES_BTN_COL_4 WS_RES_BTN_COL_3+WS_RES_BTN_SPACE_WIDTH+WS_RES_BTN_SPACE_X

#endif /* defined(_GUARD_PROJECTwordlesolvenda_FILEmain_) */
